<script lang="ts">
import { browser } from "$app/environment";
import { defineCustomElements } from "@apexui/web-components/loader";
if (browser) defineCustomElements();
const chartData = "[{ \"label\": \"Tokens\", \"value\": 92 }, { \"label\": \"Components\", \"value\": 84 }, { \"label\": \"Routes\", \"value\": 73 }]";
const rows = "[{ \"area\": \"Tokens\", \"owner\": \"Platform\", \"status\": \"Live\" }, { \"area\": \"Components\", \"owner\": \"Design system\", \"status\": \"Beta\" }, { \"area\": \"Docs\", \"owner\": \"DX\", \"status\": \"Linked\" }]";
const columns = "[{ \"key\": \"area\", \"header\": \"Area\" }, { \"key\": \"owner\", \"header\": \"Owner\" }, { \"key\": \"status\", \"header\": \"Status\" }]";
</script>
<main class="demo-shell" data-apex-theme="mint-light"><div class="demo-frame"><apex-app-bar title="ApexUI Svelte Lab"><apex-button size="sm">Run</apex-button></apex-app-bar><section class="demo-hero"><div class="demo-panel"><apex-stack gap="md"><apex-badge tone="info">Svelte custom elements</apex-badge><apex-typography as="h1" variant="display">Direct tags with Svelte route state</apex-typography><apex-typography variant="body">Svelte consumes ApexUI custom elements directly after loader registration.</apex-typography><div class="demo-actions"><apex-button>Start workflow</apex-button><apex-button variant="secondary">Inspect event</apex-button></div><apex-textarea label="Notes" default-value="Custom elements keep attributes, slots, and DOM events open."></apex-textarea></apex-stack></div><apex-card eyebrow="Runtime" title="Browser loader"><apex-progress label="Registration" value="93"></apex-progress><apex-switch label="Scoped theme" checked></apex-switch></apex-card></section><section class="demo-grid"><apex-chart label="Svelte support" data={chartData}></apex-chart><apex-tree-view items='["Routes","Stores","Custom elements"]'></apex-tree-view><apex-alert tone="info" title="Slots">Normal slots compose ApexUI tags.</apex-alert></section><apex-data-table caption="Svelte matrix" columns={columns} rows={rows}></apex-data-table><apex-alert tone="success" title="Svelte demo live">This repo installs @apexui/web-components from npm.</apex-alert></div></main>
